### ISSUE TITLE
Lv1. 리뷰

### ISSUE THREAD

**Issue by doyoung1002** [soolovepat/Todo-List#1]
1. 컴포넌트에 정리가 필요하다고 생각합니다.

-  현재 기능별로 나눠지긴했지만, 좀 더 세분화해서 파일별로 나누었으면 좋겠습니다.

2. 유효성 검사를 추가했으면 좋겠습니다.

- 입력을 안했을 때 생성이 안되는 걸로 하면 좋겠습니다.

**Comment by soolovepat** [comment]
좋은 의견입니다 ! 유효성 검사 추가 완료했습니다 :)

**Comment by soolovepat** [comment]
styled-components를 파일 분리하였습니다 ! 감사합니다👍
