### ISSUE TITLE
LV2 페어리뷰 입니다.

### ISSUE THREAD

**Issue by TheON2** [soolovepat/Todo-List#2]
1. 각 컴포넌트에 선언된 스타일드 컴포넌트를 따로 분리하면 더 좋을 것 같습니다!
- 물론 이미 훌륭한 코드입니다! 그러나, 이렇게 수정해주신다면
- 코드의 가독성을 향상 시킬 수 있습니다.
- 파일의 분리를 통해 유지보수를 용이하게 할 수 있습니다.
2. 일부 뷰에서 삼항연산자 등을 통해 코드를 효율적으로 줄일 수 있을 것 같습니다!
- 물론 이미 훌륭한 코드입니다! 그러나, 이렇게 수정해주신다면
- 가독성 향상 및 유지보수에 보다 용이할 것 같습니다.

**Comment by soolovepat** [comment]
도원님 좋은 의견 감사합니다 !
1. 스타일드 컴포넌트를 style 폴더에 따로 분리하였습니다. 적어주신대로 훨씬 정리되어 만족스럽습니다 :)
2. TodoCreate.jsx파일의 handleAddTodo 함수 if문을 삼항연산자로 축약하였습니다.
